mercure:
    hubs:
        default:
            url: '%env(MERCURE_PUBLISH_URL)%'
            public_url: '%env(MERCURE_SUBSCRIBE_URL)%'
            jwt:
                secret: '%env(string:MERCURE_JWT_SECRET)%'
                publish: '*'
                subscribe: '*'
